### PR TITLE
Splits analysis

### PR DESCRIPTION
**Pull request by mbertani**
- Restructured the environment files
- Added the split analysis notebook
- Improved the readme with instructions for the workshop participants
- Improved the auto-ml notebook

We will need a short end-to-end testing:
- Delete your conda environments locally
- Recreate all environments agaiin
- Run each notebook in their corresponding environment

### CODE REVIEW

**Comment by ferenckata** [comment]
I tried running it on another computer and that resulted in conflict of incompatible packages

**Comment by ferenckata** [comment]
In the meantime the other computer decided it actually don't mind the conflict and went through second time

**Comment by ferenckata** [comment]
conda activate ml_eda or ml_data_validation or any other extra environment does not seem to work
"could not find conda environment: ml_data_validation"

**Comment by mbertani** [comment]
> conda activate ml_eda or ml_data_validation or any other extra environment does not seem to work "could not find conda environment: ml_data_validation"

Hmm... that is strange. So  you created the environments with `conda env update -f <environment>.yaml` and then the `conda activate <environment>` didn't work at all? Should we have a talk today and see the error together?

**Comment by ferenckata** [comment]
I just followed the README which did not include this step. Now I did the conda env update -f <environment>.yaml and it works, so I also added to the README. Checked EDA, works fine :)

**Comment by mbertani** [comment]
> I just followed the README which did not include this step. Now I did the conda env update -f .yaml and it works, so I also added to the README. Checked EDA, works fine :)

OK, I have added a change in the make file, and it will create all the environments in this step. I have added a script to add all environments to jupyter lab, so that we can just choose them from the drop-down. Coming in next push. After that I merge to main and send email to participants.

**Pull request merged**
